# Generated by Django 4.0.6 on 2022-08-09 14:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='noslug', max_length=250, unique_for_date='created')),
                ('complain', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('updates', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='department', chained_model_field='department', on_delete=django.db.models.deletion.CASCADE, to='account.staffprofile')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainant', to='account.complainantprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_department', to='complaint.department')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
