# Generated by Django 4.0.6 on 2022-08-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complainantprofile',
            name='complainant_id',
        ),
    ]
