# Generated by Django 4.0.6 on 2022-08-15 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
        ('account', '0003_remove_complainantprofile_complainant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPLAINANT', 'Complainant'), ('STAFF', 'Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='of_department', to='complaint.department'),
        ),
    ]
